language: node_js
node_js: 
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: deploy
  on:
    branch: master
