language: node_js
node_js: 
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run build
deploy:
  fqdn: "j1ah0ng.xyz"
  strategy: git
  provider: pages
  local_dir: public
  github-token: $GITHUB_TOKEN
  keep_history: true
  target_branch: deploy
  on:
    branch: master
