name: gh deploy

on:
  push:
    branches: ["master"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: threeal/setup-yarn-action@v2.0.0
      - name: setup pages
        uses: actions/configure-pages@v5

      - name: install dependencies
        run: yarn install

      - name: next build
        run: yarn build

      - name: copy folder
        run: |
          cp -r ./out ./deployment

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./deployment

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: deploy to gh pages
        id: deployment
        uses: actions/deploy-pages@v4

