name: deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: install dependencies
        run: yarn install

      - name: build
        run: | 
          yarn build
          ls build
          cp -r build ../
          rm -rf ./*
          rm -f .eslintrc .gitignore .yarnclean
          rm -rf .github
          cp -r ../build/* .
          ls
          git add .

      - name: commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Deploy ${{ steps.date.outputs.date }}" -a

      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "deploy"
          force: true

      - name: done
        run: echo "deploy successful!"
